spring.application.name=upimages

aws.s3.bucket-name=${S3_BUCKET_NAME:image-bucket-17272926}
aws.profile=my-user

jwt.secret=${JWT_SECRET:minha-chave-secreta-super-segura-com-pelo-menos-256-bits-ok}
jwt.expiration=86400000

